# Generated by Django 2.2.4 on 2019-09-27 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_service', models.BooleanField(default=False)),
                ('is_product', models.BooleanField(default=False)),
                ('is_offer', models.BooleanField(default=False)),
                ('Bussiness_name', models.CharField(max_length=150)),
                ('Discription', models.TextField(max_length=200)),
                ('tag_line', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('Fixed_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('offer_startdate', models.DateField()),
                ('offer_endDate', models.DateField()),
                ('offer_starttime', models.TimeField()),
                ('offer_endtime', models.TimeField()),
                ('contact_time', models.DateTimeField()),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location_map', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('immage1', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('immage2', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('immage3', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('immage4', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('immage5', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('stock', models.IntegerField()),
                ('video_url', models.URLField()),
                ('termsandconditons', models.TimeField()),
                ('is_aggrement', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Categories')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contacts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
