# Generated by Django 2.2.4 on 2019-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, max_length=150, null=True)),
                ('subcategorie1', models.CharField(blank=True, max_length=150, null=True)),
                ('subcategorie2', models.CharField(blank=True, max_length=150, null=True)),
                ('subcategorie3', models.CharField(blank=True, max_length=150, null=True)),
                ('subcategorie4', models.CharField(blank=True, max_length=150, null=True)),
                ('subcategorie5', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
